## QFT as simple matrix vector multiplication

In [46]:
"""
We are trying to implement the QFT not on a quantum circuit basis, but rather on a mathematical basis according
to Hundt 6.2. We need to find a way to
1. create states
2. perform QFT on a state
3. perform inverse QFT on a state
We do this to perform the QFT on 1, 2 or three qubits.

As seen in Hundt's book and previous tasks, the QFT basically comes down to a matrix vector multiplication, so
we spare us the heavy mathematical part and only implement this matrix vector multiplication.
"""

import numpy as np


def omega(n):
    return np.exp(2*np.pi*1j/2**n)

def QFT(state, n):
    # n: number of qubits
    N = 2**n
    # create a n x n dimensional np.array with ones in it
    operator = np.ones((N,N), dtype=complex)
    # now fill in the lower right square of the matrix with the powers of omega
    for i in range(1,N):
        for j in range(1,N):
            operator[i,j] = omega(n)**(i*j)
    # round for better view and add normalization
    operator = np.round(operator*1/(N**0.5),4)
    result = np.round(np.matmul(operator,state),4)
    return result, operator

def inverseQFT(state,n):
    # n: number of qubits
    N = n**2
    # create a n x n dimensional np.array with ones in it
    operator = np.ones((N,N), dtype=complex)
    # now fill in the lower right square of the matrix with the powers of omega
    for i in range(1,N):
        for j in range(1,N):
            operator[i,j] = omega(n)**(-i*j)
    # round for better view and add normalization
    operator = np.round(operator*1/(N**0.5),4)
    result = np.round(np.matmul(operator,state),4)
    return result

state = np.array([1,0,0,0])
QFTstate, operator = QFT(state,2)
hermitianOp = operator.conj().T
print(f"Initial state: {state}")
print(f"QFT applied to initial state: {QFTstate}")
print(f"Inverse QFT applied to QFT state: {inverseQFT(QFTstate,2)}")
print(f"Unitary test of QFT {np.matmul(hermitianOp, QFTstate)}")



Initial state: [1 0 0 0]
QFT applied to initial state: [0.5+0.j 0.5+0.j 0.5+0.j 0.5+0.j]
Inverse QFT applied to QFT state: [1.+0.j 0.+0.j 0.+0.j 0.+0.j]
Unitary test of QFT [1.+0.j 0.+0.j 0.+0.j 0.+0.j]


Now that we have added the functions to calculate the QFT just by finding out the QFT Matrix and multiplying it to the states we can do it for 1, 2 and 3 qubits and compare to our calculation by hand from the previous tasks.

In [13]:
operator = np.ones((3,3))
operator[1,0] = 2
print(operator)

[[1. 1. 1.]
 [2. 1. 1.]
 [1. 1. 1.]]
